type = "webpack"
workers_dev = false
vars = { ENVIRONMENT = "stg" }

[site]
bucket = "./public"

[env.stg]
name = "biowasm-cdn-stg"
vars = { ENVIRONMENT = "stg" }
route = "cdn-stg.biowasm.com/*"

[env.prd]
name = "biowasm-cdn"
vars = { ENVIRONMENT = "prd" }
route = "cdn.biowasm.com/*"
