type = "webpack"
workers_dev = false
vars = { ENVIRONMENT = "stg" }

[triggers]
crons = ["*/30 * * * *"]

[env.stg]
name = "biowasm-v2-stats-stg"
vars = { ENVIRONMENT = "stg" }
route = "stats-stg.biowasm.com/*"
kv_namespaces = [
    { binding = "LOGS", id = "dd7c61572f59436796f1404eff1eec3a" }
]

[env.prd]
name = "biowasm-v2-stats"
vars = { ENVIRONMENT = "prd" }
route = "stats.biowasm.com/*"
kv_namespaces = [
    { binding = "LOGS", id = "51cfc57233574476be9cd5bb2252dc79" }
]
