type = "webpack"
workers_dev = false
vars = { ENVIRONMENT = "stg" }

[site]
bucket = "./public"
entry-point = "./entrypoint"

[env.stg]
name = "biowasm-v2-playground-stg"
vars = { ENVIRONMENT = "stg" }
route = "play-stg.biowasm.com/*"

[env.prd]
name = "biowasm-v2-playground"
vars = { ENVIRONMENT = "prd" }
route = "play.biowasm.com/*"
