name: Deploy CDN

env:
  TOOLS: (
      "seqtk 1.3 v1.3"
    )

on:
  push:
    branches: [ 13-github-actions-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2

      - name: Download Emscripten
        uses: mymindstorm/setup-emsdk@v6
        with:
          version: 1.39.1

      - name: Test Emscripten
        run: emcc -v

      # ------------------------------------------------------------------------
      # Compile
      # ------------------------------------------------------------------------
      - name: Compile to WebAssembly
        run: |
          for tool in ${TOOLS[@]};
          do
            while read toolName toolVersion toolTag;
            do
              # Go to branch/tag of interest
              cd tools/${toolName}/src
              git checkout "$toolTag"

              # Build it
              make "$toolName"
              ls -lah tools/${toolName}/build/
              mkdir -p public/${toolName}/1.3/ public/${toolName}/latest/
              cp tools/${toolName}/build/* public/${toolName}/${toolVersion}/
              cp tools/${toolName}/build/* public/${toolName}/latest/
            done <<< $tool
          done

      # ------------------------------------------------------------------------
      # Deploy to Cloudflare Workers
      # ------------------------------------------------------------------------
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
