name: Deploy biowasm

on:
  push:
    branches: [ 13-github-actions-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CDN
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2

      - name: Download Emscripten
        uses: mymindstorm/setup-emsdk@v6
        with:
          version: 1.39.1

      - name: Test Emscripten
        run: emcc -v

      # ------------------------------------------------------------------------
      # Compile
      # ------------------------------------------------------------------------
      - name: Compile to WebAssembly
        run: |
          while read toolName toolVersion toolBranch;
          do
            # Go to branch/tag of interest (cleanup from previous iteration)
            cd tools/${toolName}/src && git reset --hard && git clean -f -d && git fetch --all && git checkout "$toolBranch"

            # Build it
            make "$toolName"
            ls -lah tools/${toolName}/build/
            mkdir -p public/${toolName}/${toolVersion}/ public/${toolName}/latest/
            cp tools/${toolName}/build/* public/${toolName}/${toolVersion}/
            cp tools/${toolName}/build/* public/${toolName}/latest/
          done < <(tail -n +2 cdn.tsv)

      # ------------------------------------------------------------------------
      # Deploy to Cloudflare Workers
      # ------------------------------------------------------------------------
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
