name: Deploy biowasm v2

on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CDN v2 (STG)
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
