name: Deploy CDN

on:
  push:
    branches: [ 13-github-actions-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2

      - name: Download Emscripten
        uses: mymindstorm/setup-emsdk@v6
        with:
          version: 1.39.1

      - name: Test Emscripten
        run: emcc -v

      # ------------------------------------------------------------------------
      # Compile
      # ------------------------------------------------------------------------
      - name: Compile to WebAssembly
        run: |
          #TOOLS=("seqtk:1.3:v1.3")
          #for tool in ${TOOLS[@]};
          #do
          #  toolName=$(awk -F ":" '{ print $1 }' <<< $tool)
          #  toolVersion=$(awk -F ":" '{ print $2 }' <<< $tool)
          #  
          #done
          bash --version
          make seqtk
          ls -lah tools/seqtk/build/
          mkdir -p public/seqtk/1.3/ public/seqtk/latest/
          cp tools/seqtk/build/* public/seqtk/1.3/

      # ------------------------------------------------------------------------
      # Deploy to Cloudflare Workers
      # ------------------------------------------------------------------------
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
