name: Deploy biowasm-stg

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CDN (STG)
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2

      - name: Download Emscripten
        uses: mymindstorm/setup-emsdk@v6
        with:
          version: 2.0.0

      - name: Test Emscripten
        run: emcc -v

      # ------------------------------------------------------------------------
      # Compile
      # ------------------------------------------------------------------------
      - name: Compile to WebAssembly
        run: ./compile.sh

      # ------------------------------------------------------------------------
      # Deploy to Cloudflare Workers
      # ------------------------------------------------------------------------
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'stg'
