name: Deploy biowasm-stg v2

on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CDN v2 (STG)
    steps:
      # ------------------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------------------
      - name: Checkout biowasm repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.25

      - name: Test Emscripten
        run: emcc -v

      # ------------------------------------------------------------------------
      # Compile
      # ------------------------------------------------------------------------
      - name: Compile to WebAssembly
        run: ./deploy.sh

      # ------------------------------------------------------------------------
      # Deploy to Cloudflare Workers
      # ------------------------------------------------------------------------
      - name: Deploy cdn-stg.biowasm.com/v2/
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'stg'
          preCommands: cd cloudflare/cdn
