workers_dev = true
compatibility_date = "2022-06-26"

main = "./.cloudflare/worker.mjs"
site.bucket = "./.cloudflare/public"

[[migrations]]
tag = "v1"
new_classes = ["CDNStats"]

[env.stg]
name = "biowasm-v3-stg"
kv_namespaces = [{ binding = "CDN", id = "ceb6fce5bbe54655a0ca3add95d29954" }]
durable_objects = { bindings = [{ name = "stats", class_name = "CDNStats" }] }

[env.prd]
name = "biowasm-v3"
kv_namespaces = [{ binding = "CDN", id = "2ddb9221f3e64a0a9f113971204a8675" }]
